gbz: /save/user/jmonlong/references/hprc-v1.1-mc-grch38.gbz
dist: /save/user/jmonlong/references/hprc-v1.1-mc-grch38.dist
min: /save/user/jmonlong/references/hprc-v1.1-mc-grch38.min
sample_info: sample_info.tsv
